# updated dvc.yaml

stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data_s3/raw

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data_s3/raw
    - src/data/data_preprocessing.py
    outs:
    - data_s3/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data_s3/interim
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - data_s3/processed
    - models/vectorizer.pkl

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data_s3/processed
    - src/model/model_building.py
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.pkl
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  # Add the model_info.json file as an output

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/experiment_info.json
    - src/model/register_model.py